### ISSUE TITLE
Setting up everything related to cards and abilities

### ISSUE THREAD

**Issue by TheForgot3n1** [Mariostarr/Java-game-project#1]
Cards, its health and attack. Abilities and spells for it. A stored image, etc.
All of that needs to be done before the milestone.

**Comment by Danielava** [comment]
okok so what we meant by this was that we were gonna implement some abilities to attacks so that these attacks would cause some stuff like poision, burning, healing etc on enemies/users. But we figured out it would be best to save this for when the whole game is finished. For now we're gonna skip this feature
